language: go
go:
  - "1.10.x" # ubuntu 18.04
  - "1.11.x" # debian buster
  - "1.x" # latest

dist: bionic

addons:
  apt:
    packages:
      - appstream-util
      - golint
      - libgtk-3-dev

install:
  - make deps

script:
  - make check
  - make
  - mkdir out
  - make prefix=out install
  - make prefix=out uninstall
  - rmdir out/*/*/*/*/* out/*/*/*/* out/*/*/* out/*/* out/* out

jobs:
  allow_failures:
    - language: node_js

  include:
    - name: "Houston CI"
      language: node_js
      node_js:
        - lts/*
      sudo: required
      services:
        - docker
      addons:
        apt:
          sources:
            - sourceline: "ppa:ubuntu-toolchain-r/test"
          packages:
            - libstdc++-5-dev
      install:
        - npm i -g @elementaryos/houston
      script:
        - houston ci
