---

language: go
go:
  - "1.10.x"  # ubuntu bionic
  - "1.11.x"  # debian buster
  - "1.x"     # latest

dist: bionic

addons:
  apt:
    packages:
      - appstream-util
      - golint
      - libgtk-3-dev
      - libxml2-utils
      - yamllint

install:
  - make deps BUILDFLAGS=-v

jobs:
  allow_failures:
    - language: node_js
    - stage: check

  include:
    - stage: build
      script: make BUILDFLAGS=-v

    - stage: check
      script: make check

    - stage: test
      script: make test BUILDFLAGS=-v

    - stage: package
      name: "Houston CI"
      language: node_js
      node_js: 10/*
      services:
        - docker
      addons:
        apt:
          sources:
            - sourceline: "ppa:ubuntu-toolchain-r/test"
          packages:
            - libstdc++-5-dev
      install:
        - npm i -g @elementaryos/houston
      script:
        - houston ci
