---

language: go
go:
  - "1.10.x"  # ubuntu bionic
  - "1.11.x"  # debian buster
  - "1.x"     # latest

dist: bionic

addons:
  apt:
    packages:
      - appstream-util
      - golint
      - libgtk-3-dev
      - libxml2-utils
      - yamllint

cache:
  directories:
    - "$GOPATH"
    - "$GOCACHE"
before_cache:
  - rm -rf "$GOPATH/src/github.com/rkoesters/xkcd-gtk"

stages:
  - build
  - check
  - test
  - package

stage: build
install:
  - make deps BUILDFLAGS=-v
script:
  - make BUILDFLAGS=-v

jobs:
  allow_failures:
    - language: node_js
    - stage: check

  include:
    - &check
      stage: check
      go: "1.10.x"
      install: skip
      script:
        - make check
    - <<: *check
      go: "1.11.x"
    - <<: *check
      go: "1.x"

    - &test
      stage: test
      go: "1.10.x"
      install: skip
      script:
        - make test
    - <<: *test
      go: "1.11.x"
    - <<: *test
      go: "1.x"

    - stage: package
      name: "Houston CI"
      language: node_js
      node_js: 10/*
      services:
        - docker
      addons:
        apt:
          sources:
            - sourceline: "ppa:ubuntu-toolchain-r/test"
          packages:
            - libstdc++-5-dev
      install:
        - npm i -g @elementaryos/houston
      script:
        - houston ci
