---

name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        go:
          - 1.11.x  # debian buster
          - 1.13.x  # ubuntu focal
          - 1.x     # latest

    name: Go ${{ matrix.go }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Set up Go module cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: |
            ${{ runner.os }}-go-${{ matrix.go }}-module-cache-${{
            hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-${{ matrix.go }}-module-cache-

      - name: Set up Go build cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ matrix.go }}-build-cache

      - name: Set up build dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y -q \
          appstream-util \
          gettext \
          golint \
          libgtk-3-dev \
          libxml2-utils \
          yamllint

      - run: make
      - run: make check
      - run: make test
