name: Go

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.13

    - run: >-
        sudo apt-get update && sudo apt-get install -y -q \
        appstream-util \
        golint \
        libgtk-3-dev \
        libxml2-utils \
        yamllint

    - run: make
    - run: make dev
    - run: make check
    - run: make test
